name: Ejecución Diaria

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar a la medianoche todos los días

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio
      uses: actions/checkout@v2

    - name: Configurar Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Instalar dependencias de Python
      run: |
        pip install nbconvert
      # Esto instalará nbconvert, pero no ejecutará el notebook.

    - name: Ejecutar Notebook
      run: |
        jupyter nbconvert --to notebook --execute hello_world.ipynb
