name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit and Push
        run: |
          git config --global user.name "emigiupponi
          git config --global user.email "emigiupponi@hotmail.com"
          git add .
          git commit -m "Actualización automática"
          git push
